name: Sync Fork with Upstream 

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/MyslZhao/microfront.git
          git fetch upstream
          git merge upstream/master --no-edit
          create_pr: false                          # 不自动创建 PR，直接合并
